# This workflow will build the Java project and upload the assets to the release.

name: Build Artefact for Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: build/libs/merged/*.jar
